apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: database-replicaset
  labels:
    app: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: database
        image: moisesalc/banco-it_talent:latest
        ports:
        - containerPort: 5432
